apiVersion: apps/v1
kind: Deployment
metadata:
  name: coolapp
  labels:
    app: coolapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coolapp
  template:
    metadata:
      labels:
        app: coolapp
    spec:
      containers:
      - name: coolapp
        image: christianhxc/coolapp:0.1
        ports:
        - containerPort: 80
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 15000
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"